### ISSUE TITLE
please add a option to use localhost

### ISSUE THREAD

**Issue by HangingWithCMM** [D4RKH0R1Z0N/gphish#3]

**Comment by D4RKH0R1Z0N** [comment]
can you please explain clearly I didn't understand?

**Comment by D4RKH0R1Z0N** [comment]
Did you mean localhost.run?

**Comment by HangingWithCMM** [comment]
No I meant local host as in like “localhost:8080”

**Comment by HangingWithCMM** [comment]
Have you added it

**Comment by D4RKH0R1Z0N** [comment]
It already runs on localhost and hosts it on Ngrok, you can remove pyngrok from the code and it will run on localhost

**Comment by D4RKH0R1Z0N** [comment]
Sorry for the late response, schools have started and I am going to school and there is a lot of homework to complete for me

**Comment by D4RKH0R1Z0N** [comment]
Sorry for the late response I have school homwork to complete

**Comment by D4RKH0R1Z0N** [comment]
I'm closing this issue, feel free to reopen this when required
